### ISSUE TITLE
Grade Homework 5

### ISSUE THREAD

**Issue by mvg2** [mvg2/astr-119-hw-5#1]
Hello @ryarza and @tangyao1123 

Please grade my homework. I ran into problems with this code...and it was mostly because I didn't have enough time to work on it to the best of my abilities. I got some answers, but I know the code itself isn't as nice as what the professor is hoping to get. I just had a really rough week/weekend.  Thank you.

-Michael G.

**Comment by tangyao1123** [comment]
graded
